### ISSUE TITLE
Add Install Only Option

### ISSUE THREAD

**Issue by rallinator7** [lodestar-cli/lodestar-action#2]
## User Story

As a developer, I would like to be able to install lodestar without running it so that I can use it in scripts.

## Description
The GitHub Action for Lodestar currently installs Lodestar if it doesn't exist on the machine and then runs a command.  This is good for workflows that holds all of its logic inside of the actual workflow, but it makes lodestar unavailable to scripts that want to call in inside of the workflow.   If a user were to run the action without supplying a command, the workflow would fail due to incorrect parameters. We need to add an additional argument or command that tells the action that you just want to setup lodestar but not run a command without failing.

If a command is added to the action that does a plain install, we will have to mark the current mandatory parameters as non-mandatory.  The only parameter that would be mandatory would be the command parameter.  Because we are removing parameter checking from the action side, we will need to implement it in the actual action.

## Tasks
- [x] Add Command that does a regular install
- [x] Update action.yaml so that it doesn't require unnecessary parameters
- [x] Add Checking to the action to make sure parameters exist when needed
